# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdacf9085573316a54685a86ab22a9524fcd6738a90932d1937144eefff2b018a93f65ff615842c3020317f73dbd7bf1a2ff55e81fdb45660e3f6a7bf8a0227b

test:
  secret_key_base: bce0a416f37b46676e4a683000613644bf556c624a34c5a16ce4c36fa9ad76e829eeb42020273ae05431c56151f4a8254c37568f2d2bdf204f9cebaf1267834e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
